-- AIT 524 Week 12 
--Assignment 11
--TANMOY CHOWDHURY
--G01025893


-- Problem 01
SELECT P.PLAYER_ID, 
SUBSTR(UPPER(P.FIRST_NAME),1,1) || SUBSTR(UPPER(P.LAST_NAME),1,1) "NAME INITIALS",
C.CATEGORY_ID
FROM PLAYER P, PLAYERCAT C
WHERE P.PLAYER_ID= C.PLAYER_ID;
--TANMOY CHOWDHURY

--Problem 02
SELECT CONCAT(INITCAP(P.FIRST_NAME), CONCAT(' ',(INITCAP(P.LAST_NAME)))) "NAME", 
D.DRILL_TYPE  "DRILL TYPE"
FROM PLAYER P 
JOIN PLAYERCAT PC ON P.PLAYER_ID = PC.PLAYER_ID
JOIN CAT_DRILL CD ON PC.CATEGORY_ID = CD.CATEGORY_ID
JOIN DRILL D ON CD.DRILL_ID = D.DRILL_ID;
--TANMOY CHOWDHURY

--Problem 03
SELECT P.PLAYER_ID, G.PLAYER_TYPE,
SUBSTR(P.EMAIL, INSTR(P.EMAIL, '@')+1, LENGTH(P.EMAIL)) "EMAIL DOMAIN"
FROM PLAYER P 
JOIN GOALKEEPER G ON P.PLAYER_ID = G.PLAYER_ID;
--TANMOY CHOWDHURY

--Problem 04
SELECT LOWER(P.FIRST_NAME) "NAME", S.PLAYER_TYPE,
TRANSLATE(S.PLAYER_TYPE,'STRICKER', 'GMACHINA') "NEW TYPE"
FROM PLAYER P 
JOIN STRICKER S ON P.PLAYER_ID = S.PLAYER_ID;
--TANMOY CHOWDHURY

--Problem 05
SELECT P.AGE, COUNT(P.AGE) "NO. OF PLAYER"
FROM PLAYER P
GROUP BY P.AGE;
--TANMOY CHOWDHURY

--Problem 06
SELECT P.AGE, COUNT(P.AGE) "NO. OF PLAYER"
FROM PLAYER P
WHERE P.AGE IN (19, 23,25)
GROUP BY P.AGE;
--TANMOY CHOWDHURY

--Problem 07
SELECT P.AGE, COUNT(P.AGE) "NO. OF PLAYER"
FROM PLAYER P
WHERE P.AGE IN (19, 23,25)
GROUP BY P.AGE
HAVING P.AGE>23;
--TANMOY CHOWDHURY

--Problem 08
SELECT MAX(P.AGE) "MAXIMUM AGE", C.CATEGORY_ID
FROM PLAYER P
JOIN PLAYERCAT C ON P.PLAYER_ID= C.PLAYER_ID
GROUP BY C.CATEGORY_ID;
--TANMOY CHOWDHURY

--Problem 09
SELECT MAX(P.AGE) "MAXIMUM AGE", C.CATEGORY_ID
FROM PLAYER P
JOIN PLAYERCAT C ON P.PLAYER_ID= C.PLAYER_ID
WHERE P.AGE IN (19, 23,25)
GROUP BY C.CATEGORY_ID;
--TANMOY CHOWDHURY

--Problem 10
SELECT MAX(P.AGE) "MAXIMUM AGE", C.CATEGORY_ID
FROM PLAYER P
JOIN PLAYERCAT C ON P.PLAYER_ID= C.PLAYER_ID
WHERE P.AGE IN (19, 23,25)
GROUP BY C.CATEGORY_ID
HAVING MAX(P.AGE)>23;
--TANMOY CHOWDHURY
