-- AIT 524 Week 12
--TANMOY CHOWDHURY
--G01025893

--Practice Problem: Selected Single-Row Function

--Problem 1
SELECT 'TANMOY CHOWDHURY'
FROM DUAL;

--Problem 2
SELECT INITCAP('TANMOY CHOWDHURY')
FROM DUAL;

--Problem 3
SELECT INSTR('TANMOY CHOWDHURY', ' ')
FROM DUAL;

--Problem 4
SELECT SUBSTR('TANMOY CHOWDHURY', 8, 9)
FROM DUAL;

--Problem 5
SELECT SUBSTR('TANMOY CHOWDHURY', 1, INSTR('TANMOY CHOWDHURY', ' '))
FROM DUAL;

--Problem 6
SELECT SUBSTR('TANMOY CHOWDHURY', INSTR('TANMOY CHOWDHURY', ' '), LENGTH('TANMOY CHOWDHURY'))
FROM DUAL;

--Problem 7
SELECT CONCAT(CONCAT('TANMOY', ' '), 'CHOWDHURY') 
FROM DUAL;

-- Problem 8
SELECT TRUNC(MONTHS_BETWEEN('24-DEC-18', SYSDATE),0) 
FROM DUAL;

-- Problem 9
SELECT TO_DATE('JANUARY 21, 2013', 'MONTH DD, YYYY') 
FROM DUAL;

-- Problem 10
SELECT TO_CHAR(TO_DATE('21-JAN-13', 'DD MONTH, YY'), 'MONTH DD, YYYY') 
FROM DUAL;

------------------------------------------------------------------------
--Practice Problem: Group Function
--Problem 1
SELECT AVG(COST), MAX(DISTINCT COST), MIN(DISTINCT COST) 
FROM BOOKS;

--Problem 2
SELECT COUNT(SHIPCOST) "SHIPCOST COUNT", COUNT(*) "TOTAL ORDERS COUNT"
FROM ORDERS;
--Alternate Solution
SELECT COUNT(DISTINCT CATEGORY)"NON-NULL CATEGORY COUNT", COUNT(*) "TOTAL CATEGORY" 
FROM BOOKS;

--Problem 3
SELECT ORDERDATE, TO_CHAR(AVG(SHIPCOST), '999.99') "AVERAGE SHIP COST" 
FROM ORDERS 
WHERE ORDERDATE > '01-JAN-01'
GROUP BY ORDERDATE 
HAVING AVG(SHIPCOST)>0;

--Alternate Solution
SELECT CATEGORY, TO_CHAR(AVG(RETAIL-COST), '999.99') "PROFIT" 
FROM BOOKS 
WHERE PUBDATE > '14-DEC-05'
GROUP BY CATEGORY 
HAVING AVG(RETAIL-COST)>15;

--Problem 4
SELECT SHIPDATE, ORDERDATE, TO_CHAR(AVG(SHIPCOST), '999.99') "AVERAGE SHIP COST" 
FROM ORDERS 
WHERE ORDERDATE > '01-JAN-01'
GROUP BY ROLLUP(SHIPDATE, ORDERDATE)
HAVING AVG(SHIPCOST)>0
ORDER BY (SHIPDATE);

--Alternate Solution
SELECT TITLE, CATEGORY, TO_CHAR(AVG(RETAIL-COST), '999.99') "PROFIT" 
FROM BOOKS 
WHERE PUBDATE > '14-DEC-05'
GROUP BY ROLLUP (TITLE, CATEGORY)
HAVING AVG(RETAIL-COST)>15;

--Problem 5
SELECT SHIPDATE, ORDERDATE, TO_CHAR(AVG(SHIPCOST), '999.99') "AVERAGE SHIP COST" 
FROM ORDERS 
WHERE ORDERDATE > '01-JAN-01'
GROUP BY CUBE(SHIPDATE, ORDERDATE)
HAVING AVG(SHIPCOST)>0
ORDER BY (SHIPDATE);

--Alternate Solution
SELECT TITLE, CATEGORY, TO_CHAR(AVG(RETAIL-COST), '999.99') "PROFIT" 
FROM BOOKS 
WHERE PUBDATE > '14-DEC-05'
GROUP BY CUBE (TITLE, CATEGORY)
HAVING AVG(RETAIL-COST)>15;


























