
-- AIT 524 Week 09 
--Assignment 08
--TANMOY CHOWDHURY

--DROP TABLE (For deleting table with definition, cannot be undone)
--FLASHBACK TABLE (For recoving from recycle bin)

-- DROP all the tables that are going to be used in this assignment.
-- For ensuring there is no duplicate table as like the assignment.
 
 
DROP TABLE GOALKEEPER_BEGINNER; 
DROP TABLE GOALKEEPER_INTERMEDIATE; 
DROP TABLE GOALKEEPER_EXPERT;
DROP TABLE GOALKEEPER; 

DROP TABLE DEFENSE_BEGINNER; 
DROP TABLE DEFENSE_INTERMEDIATE; 
DROP TABLE DEFENSE_EXPERT;
DROP TABLE DEFENSE; 

DROP TABLE STRICKER_BEGINNER; 
DROP TABLE STRICKER_INTERMEDIATE; 
DROP TABLE STRICKER_EXPERT;
DROP TABLE STRICKER; 

DROP TABLE PLAYERCAT; 
DROP TABLE CAT_DRILL;

DROP TABLE PLAYER;
DROP TABLE CATEGORY; 
DROP TABLE DRILL; 

-- Create Table Definition
CREATE TABLE PLAYER
(PLAYER_ID  VARCHAR2(8) NOT NULL,
FIRST_NAME VARCHAR2(15) NOT NULL,
LAST_NAME VARCHAR2(15) NOT NULL,
EMAIL VARCHAR2(50) NOT NULL,
AGE NUMBER(4),
  CONSTRAINT PLAYER_PLAYER_ID_PK PRIMARY KEY(PLAYER_ID));
		
CREATE TABLE GOALKEEPER
(PLAYER_ID  VARCHAR2(8) NOT NULL REFERENCES PLAYER(PLAYER_ID),
PLAYER_TYPE CHAR(12) NOT NULL,
  CONSTRAINT GOALKEEPER_PLAYER_ID_PK PRIMARY KEY(PLAYER_ID),
  CONSTRAINT GOALKEEPER_PLAYER_TYPE_CK CHECK (PLAYER_TYPE = 'GOALKEEPER'));
  
CREATE TABLE GOALKEEPER_BEGINNER
(PLAYER_ID  VARCHAR2(8) NOT NULL REFERENCES PLAYER(PLAYER_ID),
PLAYER_TYPE CHAR(12) NOT NULL,
PLAYER_LEVEL CHAR(8) NOT NULL,
  CONSTRAINT GOALKEEPER_BEG_PLAYER_ID_PK PRIMARY KEY(PLAYER_ID),
  CONSTRAINT GOALKEEPER_BEG_PLAYER_TYPE_CK CHECK (PLAYER_TYPE = 'GOALKEEPER' AND PLAYER_LEVEL = 'BEGINNER'));
  
CREATE TABLE GOALKEEPER_INTERMEDIATE
(PLAYER_ID  VARCHAR2(8) NOT NULL REFERENCES PLAYER(PLAYER_ID),
PLAYER_TYPE CHAR(12) NOT NULL,
PLAYER_LEVEL CHAR(16) NOT NULL,
  CONSTRAINT GOALKEEPER_INT_PLAYER_ID_PK PRIMARY KEY(PLAYER_ID),
  CONSTRAINT GOALKEEPER_INT_PLAYER_TYPE_CK CHECK (PLAYER_TYPE = 'GOALKEEPER' AND PLAYER_LEVEL = 'INTERMEDIATE'));
  
CREATE TABLE GOALKEEPER_EXPERT
(PLAYER_ID  VARCHAR2(8) NOT NULL REFERENCES PLAYER(PLAYER_ID),
PLAYER_TYPE CHAR(12) NOT NULL,
PLAYER_LEVEL CHAR(16) NOT NULL,
  CONSTRAINT GOALKEEPER_EXP_PLAYER_ID_PK PRIMARY KEY(PLAYER_ID),
  CONSTRAINT GOALKEEPER_EXP_PLAYER_TYPE_CK CHECK (PLAYER_TYPE = 'GOALKEEPER' AND PLAYER_LEVEL = 'EXPERT'));
  
CREATE TABLE DEFENSE
(PLAYER_ID  VARCHAR2(8) NOT NULL REFERENCES PLAYER(PLAYER_ID),
PLAYER_TYPE CHAR(12) NOT NULL,
  CONSTRAINT DEFENSE_PLAYER_ID_PK PRIMARY KEY(PLAYER_ID),
  CONSTRAINT DEFENSE_PLAYER_TYPE_CK CHECK (PLAYER_TYPE = 'DEFENSE'));
  
CREATE TABLE DEFENSE_BEGINNER
(PLAYER_ID  VARCHAR2(8) NOT NULL REFERENCES PLAYER(PLAYER_ID),
PLAYER_TYPE CHAR(12) NOT NULL,
PLAYER_LEVEL CHAR(8) NOT NULL,
  CONSTRAINT DEFENSE_BEG_PLAYER_ID_PK PRIMARY KEY(PLAYER_ID),
  CONSTRAINT DEFENSE_BEG_PLAYER_TYPE_CK CHECK (PLAYER_TYPE = 'DEFENSE' AND PLAYER_LEVEL = 'BEGINNER'));
  
CREATE TABLE DEFENSE_INTERMEDIATE
(PLAYER_ID  VARCHAR2(8) NOT NULL REFERENCES PLAYER(PLAYER_ID),
PLAYER_TYPE CHAR(12) NOT NULL,
PLAYER_LEVEL CHAR(16) NOT NULL,
  CONSTRAINT DEFENSE_INT_PLAYER_ID_PK PRIMARY KEY(PLAYER_ID),
  CONSTRAINT DEFENSE_INT_PLAYER_TYPE_CK CHECK (PLAYER_TYPE = 'DEFENSE' AND PLAYER_LEVEL = 'INTERMEDIATE'));
  
CREATE TABLE DEFENSE_EXPERT
(PLAYER_ID  VARCHAR2(8) NOT NULL REFERENCES PLAYER(PLAYER_ID),
PLAYER_TYPE CHAR(12) NOT NULL,
PLAYER_LEVEL CHAR(16) NOT NULL,
  CONSTRAINT DEFENSE_EXP_PLAYER_ID_PK PRIMARY KEY(PLAYER_ID),
  CONSTRAINT DEFENSE_EXP_PLAYER_TYPE_CK CHECK (PLAYER_TYPE = 'DEFENSE' AND PLAYER_LEVEL = 'EXPERT'));
  
CREATE TABLE STRICKER
(PLAYER_ID  VARCHAR2(8) NOT NULL REFERENCES PLAYER(PLAYER_ID),
PLAYER_TYPE CHAR(12) NOT NULL,
  CONSTRAINT STRICKER_PLAYER_ID_PK PRIMARY KEY(PLAYER_ID),
  CONSTRAINT STRICKER_PLAYER_TYPE_CK CHECK (PLAYER_TYPE = 'STRICKER'));
  
CREATE TABLE STRICKER_BEGINNER
(PLAYER_ID  VARCHAR2(8) NOT NULL REFERENCES PLAYER(PLAYER_ID),
PLAYER_TYPE CHAR(12) NOT NULL,
PLAYER_LEVEL CHAR(8) NOT NULL,
  CONSTRAINT STRICKER_BEG_PLAYER_ID_PK PRIMARY KEY(PLAYER_ID),
  CONSTRAINT STRICKER_BEG_PLAYER_TYPE_CK CHECK (PLAYER_TYPE = 'STRICKER' AND PLAYER_LEVEL = 'BEGINNER'));
  
CREATE TABLE STRICKER_INTERMEDIATE
(PLAYER_ID  VARCHAR2(8) NOT NULL REFERENCES PLAYER(PLAYER_ID),
PLAYER_TYPE CHAR(12) NOT NULL,
PLAYER_LEVEL CHAR(16) NOT NULL,
  CONSTRAINT STRICKER_INT_PLAYER_ID_PK PRIMARY KEY(PLAYER_ID),
  CONSTRAINT STRICKER_INT_PLAYER_TYPE_CK CHECK (PLAYER_TYPE = 'STRICKER' AND PLAYER_LEVEL = 'INTERMEDIATE'));
  
CREATE TABLE STRICKER_EXPERT
(PLAYER_ID  VARCHAR2(8) NOT NULL REFERENCES PLAYER(PLAYER_ID),
PLAYER_TYPE CHAR(12) NOT NULL,
PLAYER_LEVEL CHAR(16) NOT NULL,
  CONSTRAINT STRICKER_EXP_PLAYER_ID_PK PRIMARY KEY(PLAYER_ID),
  CONSTRAINT STRICKER_EXP_PLAYER_TYPE_CK CHECK (PLAYER_TYPE = 'STRICKER' AND PLAYER_LEVEL = 'EXPERT'));
  
CREATE TABLE CATEGORY
(CATEGORY_ID  VARCHAR2(8) NOT NULL,
PLAYER_TYPE CHAR(12) NOT NULL,
PLAYER_LEVEL CHAR(16) NOT NULL,
  CONSTRAINT CATEGORY_CATEGORY_ID_PK PRIMARY KEY(CATEGORY_ID));
    
 CREATE TABLE PLAYERCAT
(PLAYER_ID  VARCHAR2(8) NOT NULL,
 CATEGORY_ID VARCHAR2(20) NOT NULL,
 	CONSTRAINT PLAYERCAT__PK PRIMARY KEY (PLAYER_ID, CATEGORY_ID),
 	CONSTRAINT PLAYERCAT_PLAYER_ID_FK FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(PLAYER_ID),
 	CONSTRAINT PLAYERCAT_CATEGORY_ID_ID_FK FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID));

CREATE TABLE DRILL
(DRILL_ID  VARCHAR2(20) NOT NULL,
DRILL_TYPE CHAR(10) NOT NULL,
DRILL_DURATION NUMBER(3) NOT NULL,
  CONSTRAINT DRILL_DRILL_ID_PK PRIMARY KEY(DRILL_ID),
  CONSTRAINT DRILL_DRILL_TYPE_CK CHECK (DRILL_TYPE = 'PASSING' OR DRILL_TYPE = 'DRIBBLING' OR DRILL_TYPE = 'SHOOTING'));

		
 CREATE TABLE CAT_DRILL
(CATEGORY_ID VARCHAR2(20) NOT NULL,
 DRILL_ID  VARCHAR2(20) NOT NULL,
 	CONSTRAINT CAT_DRILL__PK PRIMARY KEY (CATEGORY_ID, DRILL_ID),
 	CONSTRAINT CAT_DRILL_DRILL_ID_FK FOREIGN KEY (DRILL_ID) REFERENCES DRILL(DRILL_ID),
 	CONSTRAINT CAT_DRILL_CATEGORY_ID_ID_FK FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID));
	